# Generated by Django 6.0 on 2026-01-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "DRAFT"), ("PUBLISHED", "PUBLISHED")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
