# Generated by Django 6.0 on 2026-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_title", models.CharField(max_length=25)),
                ("about_description", models.TextField(max_length=200)),
            ],
        ),
    ]
